#!/usr/bin/env bash

NAME=semaphore-s2-vm

for i in {1..400}; do

   mac_address=$(sudo virsh dumpxml $NAME | grep "mac address" | sed "s/.*'\\(.*\\)'.*/\\1/g")
   ip=$(arp -an | grep $mac_address | awk '{ gsub(/[\\(\\)]/,"",$2); print $2 }')

   if [ -z $ip ]; then
     sleep 1
   else
     echo $ip
     break;
   fi

 done
