#!/bin/bash

# Misc
DATE_FORMAT='%H:%M %d/%m/%Y'
declare -A sem_services
sem_services['memcached']="1.5 1.6"
sem_services['mysql']="5.5 5.6.52 5.6 5.6.50 5.7.27 5.7.31 5.7.32 5.7 5 8.0.22 8.0 8"
sem_services['redis']="2.8.23 2.8 2 3.2.4 3.2.12 3.2 3 4.0.12 4.0.14 4.0 4 5.0.6 5.0.9 5.0 5 6.0.5 6.0.8 6.0 6"
sem_services['mongo']="3.2.1 3.2 3.6.20 3.6 3 4.0.20 4.0 4.1.13 4.1 4.2.10 4.2 4.4.1 4.4 4"
sem_services['elasticsearch']="1.7.6 1.7 1 2.4.6 2.4 2 5.4.3 5.4 5.5.2 5.5 5.6.16 5.6 5 6.5.1 6.5.4 6.5 6.8.1 6.8.13 6.8 6 7.1.1 7.1 7.2.0 7.2 7.2.1 7.2 7.3.1 7.3.2 7.3 7.4.2 7.4 7.5.0 7.5.1 7.5.2 7.5 7.6.0 7.6.2 7.6 7.7.0 7.7.1 7.7 7.8.1 7.8 7.9.0 7.9.2 7.9.3 7.9 7"
sem_services['postgres']="9.4.26 9.4 9.5.15 9.5.23 9.5 9.6.6 9.6.11 9.6.18 9.6.19 9.6 9 10.0 10.5 10.6 10.7 10.11 10.12 10.13 10.14 10 11.0 11.2 11.5 11.6 11.7 11.8 11.9 11 12.1 12.2 12.3 12.4 12 13.0 13"
sem_services['rabbitmq']="3.6.16 3.6 3.8.2 3.8.9 3.8 3"
sem_services['cassandra']="3.11.3 3.11.8 3.11 3"
sem_services['rethinkdb']="2.3.6 2.3 2.4.1 2.4 2"
sem_services['postgis']="9.5-2.5 9.5-3.0 9.6-2.5 9.6-3.0 10-2.5 10-3.0 11-2.5 11-3.0 12-2.5 12-3.0 13-3.0"

service::pull_image() {
  local image_name=$1

  if [[ -z $image_name ]]; then
    service:err "Image name can't be empty"
  fi

#  if ! echo $image_name | grep -E '^[[:alnum:]]+(:[[:alnum:]]+.*)?$' &>/dev/null; then
#    service::err "Invalid image name provided '${image_name}'"
#  fi

  service::duration service::run_cmd docker pull $image_name download $(echo ${image_name%%:*})
}
service::check_version(){
  local version="$2"
  local image_name="$1"
  local have_it=1
  local local_versions="${sem_services[$image_name]}"
  for i in ${local_versions[@]};do
    if [ "$version" == "$i" ];then
      have_it=0
      break
    fi
  done
########### Output message if we dont host the image
#  if [ $have_it -eq 1 ]; then
#    service::err "We dont provide version: $version. Available versions for $image_name: $local_versions"
#  fi
  echo $have_it
}


service::start_mysql() {
  service_version=$1
  shift
  local service_image='mysql'
  if [ "$(service::check_version 'mysql' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  docker_params="$@"
  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run $docker_params $service_image:$service_version)
  # run only if previous command exited successfully
  service::duration sem-dockerize 3306 boot mysql

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "MySQL $service_version is running at 0.0.0.0:3306"

}

service::start_postgres() {
  service_version=$1
  shift
  local service_image='postgres'
  if [ "$(service::check_version 'postgres' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  docker_params="$@"
  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run $docker_params $service_image:$service_version)
  # run only if previous command exited successfully
  service::duration sem-dockerize 5432 boot postgres
  echo "done."
  echo "PostgreSQL $service_version is running at 0.0.0.0:5432"

}

service::start_postgis() {
  service_version=$1
  shift
  local service_image='postgis'
  if [ "$(service::check_version 'postgis' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  else
    service_image="postgis/$service_image"
  fi

  docker_params="$@"
  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run $docker_params "$service_image:$service_version")
  # run only if previous command exited successfully
  service::duration sem-dockerize 5432 boot postgis
  echo "done."
  echo "PostgreSQL with postgis $service_version is running at 0.0.0.0:5432"

}

service::start_redis() {
  service_version=$1
  shift

  local service_image='redis'
  if [ "$(service::check_version 'redis' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  docker_params="$@"
  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run $docker_params $service_image:$service_version)
  # run only if previous command exited successfully
  service::duration sem-dockerize 6379 boot redis

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "Redis $service_version is running at 0.0.0.0:6379"

}

service::start_memcached() {
  service_version="${1:-1.5}"
  local service_image='memcached'
  if [ "$(service::check_version 'memcached' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run --net=host --rm --name memcached -d $service_image:$service_version)
  # run only if previous command exited successfully
  service::duration sem-dockerize 11211 boot memcached

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "memcached $service_version is running at 0.0.0.0:11211"

}

service::start_mongodb() {
  service_version=$1
  shift
  local service_image='mongo'
  if [ "$(service::check_version 'mongo' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  docker_params="$@"
  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run $docker_params $service_image:$service_version)
  # run only if previous command exited successfully
  service::duration sem-dockerize 27017 -timeout 30s 2>/dev/null boot mongodb

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "mongodb $service_version is running at 0.0.0.0:27017"

}

service::start_elasticsearch() {
  service_version="${1:-6.5.1}"
  local service_image='elasticsearch'
  if [ "$(service::check_version 'elasticsearch' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run --net=host --rm --name elasticsearch -e "discovery.type=single-node" -d $service_image:$service_version)

  # run only if previous command exited successfully
  service::duration sem-dockerize 9200 boot elasticseach

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "elasticsearch $service_version is accessible at 0.0.0.0:9200 and 0.0.0.0:9300"

}

service::start_rabbitmq() {
  service_version="${1:-3.8.2}"
  local service_image='rabbitmq'
  if [ "$(service::check_version 'rabbitmq' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run --net=host --rm --name rabbitmq --hostname rabbitmq -d $service_image:$service_version)

  # run only if previous command exited successfully
  service::duration sem-dockerize 5672 boot rabbitmq

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "rabbitmq $service_version is accessible at 0.0.0.0:5672"

}

service::start_cassandra() {
  service_version="${1:-3.11.3}"
  local service_image='cassandra'
  if [ "$(service::check_version 'cassandra' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run --net=host --rm --name cassandra -d $service_image:$service_version)

  # run only if previous command exited successfully
  service::duration sem-dockerize 9042 boot cassandra

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "cassandra $service_version is accessible at 0.0.0.0:9042"

}

service::start_rethinkdb() {
  service_version="${1:-2.3.6}"
  local service_image='rethinkdb'
  if [ "$(service::check_version 'rethinkdb' $service_version)" == "0" ]; then
    service_image="registry.semaphoreci.com/$service_image"
  fi

  service::pull_image "$service_image:$service_version"
  docker_output=$(docker run --net=host --rm --name rethinkdb -d $service_image:$service_version)

  # run only if previous command exited successfully
  service::duration sem-dockerize 28015 boot rethinkdb

  # if not started in 30 seconds print logs and exit
  echo "done."
  echo "rethinkdb $service_version is accessible at 0.0.0.0:28015"

}

service::start() {
  service_name=$1
  service_version=$2
  if [ -z "$service_name" ]; then
    service::print_usage
    exit 1
  fi

  echo -n "Starting $service_name..."

  case "$service_name" in
    "mysql" )
      shift

      service_version=$(sem-service-check-params mysql $@)
      service::duration service::start_mysql $service_version total $service_name
      exit 0
      ;;
    "postgres" )
      shift

      service_version=$(sem-service-check-params postgres $@)
      service::duration service::start_postgres $service_version total $service_name
      exit 0
      ;;
    "postgis" )
      shift
    
      service_version=$(sem-service-check-params postgis $@)
      service::duration service::start_postgis $service_version total $service_name
      exit 0
      ;;
    "redis" )
      shift

      service_version=$(sem-service-check-params redis $@)
      service::duration service::start_redis $service_version total $service_name
      exit 0
      ;;
    "memcached" )
      shift

      service::duration service::start_memcached $service_version total $service_name
      exit 0
      ;;
    "mongodb" )
      shift
      service_version=$(sem-service-check-params mongodb $@)
      service::duration service::start_mongodb $service_version total $service_name
      exit 0
      ;;
    "elasticsearch" )
      shift

      service::duration service::start_elasticsearch $service_version total $service_name
      exit 0
      ;;
    "rabbitmq" )
      shift

      service::duration service::start_rabbitmq $service_version total $service_name
      exit 0
      ;;
    "cassandra" )
      shift

      service::duration service::start_cassandra $service_version total $service_name
      exit 0
      ;;
    "rethinkdb" )
      shift

      service::duration service::start_rethinkdb $service_version total $service_name
      exit 0
      ;;

    * )
      service::print_usage
      exit 1
      ;;
  esac
}


service::stop() {
  local service_name
  local service_check_log

  service_name=$1
  service_check_log=$( service::status $service_name &>/dev/null )
  service_status=$?

  if [[ $service_status -eq 0 ]]; then
    stop_output=$( service::run_cmd docker stop $service_name )

    service::log "'${service_name}' stopped."
  else
    service::log "No running service with name '${service_name}' was found. Skipping."
  fi

  return 0
}


################################################################################
# Service status
# Globals:
#   none
# Arguments:
#   service_name
# Returns:
#   0,1...n
################################################################################
service::status() {
  local service_name
  local docker_ps

  service_name=$1
  docker_ps=$(docker ps | grep $service_name &>/dev/null )
  service_status=$?

  if [[ $service_status -eq 0 ]]; then
    service::log "${service_name} running."
  else
    service::log "'${service_name}' not running."
  fi

  return $service_status
}


################################################################################
# Helper for running commands with the ability to dry-run
# Globals:
#   DRYRUN
# Arguments:
#   command
# Returns:
#   0,1...n
################################################################################
service::run_cmd() {
  local cmd=$@
  local out=""
  local status=0

  if [[ -n $DRYRUN ]]; then
    service::log "Dry-running '${cmd}'"
  else
    out=$($cmd 2>&1)
    status=$?
  fi

  if ! [[ $status -eq 0 ]]; then
    service::err "Failed to run command '${cmd}'\n\nReason:\n${out}"
  fi

  return $status
}


################################################################################
# Gets port information about the running service
# Globals:
#   none
# Arguments:
#   service_name
# Returns:
#   port
################################################################################
service::port_info() {
  local service_name
  local service_check_log

  service_name=$1
  port_check_log=$( service::run_cmd sudo netstat -tlpn | grep $service_name 2>&1 )
  port_status=$?

  if [[ $service_status -eq 0 ]]; then
    listens_on=$( echo ${port_check_log} | awk '{print $4}' )

    echo "Listens on ${listens_on}"
  else
    echo "No port found for '${service_name}'."
  fi

  return 0
}

service::log() {
  echo -e "[$(date +"${DATE_FORMAT}")]: $@" >&2
}

service::err() {
  echo -e "\n! [$(date +"${DATE_FORMAT}")]: $@\n" >&2

  exit 1
}

service::print_usage() {
  echo -e "\nsem-service [start|stop|status] [service] [version]\n"

  echo "Available services:"
  echo "mysql (default: 5.6)"
  echo "postgres (default: 9.6)"
  echo "postgres with postgis (default: 9.6-2.5)"
  echo "redis (default: 4)"
  echo "memcached (default: 1.5)"
  echo "mongodb (default: 4.5)"
  echo "elasticsearch (default: 6.5.1)"
  echo "cassandra (default: 3.11.3)"
  echo "rethinkdb (default: 2.3.6)"
}

service::duration() {
  local cmd=${@:1:$#-2}
  local service=$(echo "${@: -1}")
  local type=$(echo "${@: -2:1}")
  local start
  local end
  local duration
  start=$(date +%s%3N)
  $cmd
  end=$(date +%s%3N)
  duration=$(( $end - $start ))
  echo "toolbox_sem_service_${type}_${service} ${duration}" >> /tmp/toolbox_metrics #in ms

  return 0
}

service::main () {
  case "$1" in
    "start" )
      shift

      service::start "$@"
      ;;
    "stop" )
      shift

      service::stop "$@"
      ;;
    "status" )
      shift

      service::status "$@"
      ;;
    * )
      service::print_usage
      ;;
  esac
}

service::main "$@"
