#!/usr/bin/env bash

params-check::mysql () {
  default_params='--net=host --rm -d -e MYSQL_ALLOW_EMPTY_PASSWORD=true -e MYSQL_ROOT_PASSWORD=semaphoredb --name mysql -v /var/run/mysqld:/var/run/mysqld '
  service_version="5.6"
  sudo mkdir -p /var/run/mysqld 
  sudo chmod -R 0777 /var/run/mysqld
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    username=""; password=""; db=" -e MYSQL_DATABASE="; dbname="";
    for words in $params; do
      case $words in
       --username=* )
         username=" -e MYSQL_USER=$(echo $words|cut -d'=' -f2) "
       ;;
       --password=* )
         password=" -e MYSQL_PASSWORD=$(echo $words|cut -d'=' -f2) "
       ;;
       --db=* )
         dbname=$(echo $words|cut -d'=' -f2)
       ;;
       *)
       ;;
      esac
    done
    dbname=${dbname:-'test'}
    [ "$username$password" ] && default_params="$default_params$username$password$db$dbname "
  fi
  echo "$service_version $default_params"
}

params-check::postgres () {
  default_params='--net=host --rm -d --name postgres -v /var/run/postgresql:/var/run/postgresql '
  service_version="9.6"
  sudo mkdir -p /var/run/postgresql 
   sudo chmod -R 0777 /var/run/postgresql
  username=" -e POSTGRES_USER=runner "
  password=" -e POSTGRES_PASSWORD=semaphoredb "
  db=""
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    dbname="";
    for words in $params; do
      case $words in
       --username=* )
         username_local=$(echo $words|cut -d'=' -f2)
         [ -n "$username_local" ] && username=" -e POSTGRES_USER=$username_local"
       ;;
       --password=* )
         password_local=$(echo $words|cut -d'=' -f2) 
         [ -n "$password_local" ] && password=" -e POSTGRES_PASSWORD=$password_local"
       ;;
       --db=* )
         dbname=$(echo $words|cut -d'=' -f2)
       ;;
       *)
       ;;
      esac
    done
    [ "$dbname" ] && db=" -e POSTGRES_DB=$dbname"
  fi
  default_params="$default_params$username$password$db "
  echo "$service_version $default_params"
}

params-check::postgis () {
  default_params='--net=host --rm -d --name postgis -v /var/run/postgresql:/var/run/postgresql '
  service_version="9.6-2.5"
  sudo mkdir -p /var/run/postgresql 
  sudo chmod -R 0777 /var/run/postgresql
  username=" -e POSTGRES_USER=runner "
  password=" -e POSTGRES_PASSWORD=semaphoredb "
  db=""
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    dbname="";
    for words in $params; do
      case $words in
       --username=* )
         username_local=$(echo $words|cut -d'=' -f2)
         [ -n "$username_local" ] && username=" -e POSTGRES_USER=$username_local"
       ;;
       --password=* )
         password_local=$(echo $words|cut -d'=' -f2) 
         [ -n "$password_local" ] && password=" -e POSTGRES_PASSWORD=$password_local"
       ;;
       --db=* )
         dbname=$(echo $words|cut -d'=' -f2)
       ;;
       *)
       ;;
      esac
    done
    [ "$dbname" ] && db=" -e POSTGRES_DB=$dbname"
  fi
  default_params="$default_params$username$password$db "
  echo "$service_version $default_params"
}

params-check::redis () {
  default_params='--net=host --rm --name redis -d'
  service_version="5.0.7"
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi

  echo "$service_version $default_params"
}

params-check::mongodb () {
  default_params='--net=host --rm --name mongodb -d'
  service_version="4.1"
  params=""
  if [ "${1:0:1}" == "-" ];then
    params="$@"
  else
    service_version="${1:-$service_version}"
    tmp="${@:2}"
    params="${tmp:-$default_params}"
  fi
  if [ "$default_params" != "$params" ];then
    username=""; password="" 
    for words in $params; do
      case $words in
       --username=* )
         username=$(echo $words|cut -d'=' -f2)
         [ "$username" ] && username=" -e MONGO_INITDB_ROOT_USERNAME=$username "
       ;;
       --password=* )
         password=$(echo $words|cut -d'=' -f2)
         [ "$password" ] && password=" -e MONGO_INITDB_ROOT_PASSWORD=$password "
       ;;
       *)
       ;;
      esac
    done
    default_params="$default_params$username$password "
  fi
  echo "$service_version $default_params"
}

params-check::main () {
  case "$1" in
    "mysql" )
      shift
      params-check::mysql $@
      ;;
    "postgres" )
      shift
      params-check::postgres $@
      ;;
    "postgis" )
      shift
      params-check::postgis $@
      ;;
    "redis" )
      shift
      params-check::redis $@
      ;;
    "mongodb" )
      shift
      params-check::mongodb $@
      ;;
    * )
      shift
      echo "$@"
      ;;
  esac
}

params-check::main "$@"
